### ISSUE TITLE
Tidak bisa sync 

### ISSUE THREAD

**Issue by ajengyunisa** [polinema-gui/tugas-2015-03#1]
Permisi pak maaf menggangu waktunya, saya ajeng yunisa dari MI 2E tidak bisa melakukan sync padahal sudah commit. Notifikasinya seperti ini
![a](https://cloud.githubusercontent.com/assets/11324474/10559005/22e067d8-7510-11e5-9c87-09bbfcff92cd.JPG)

**Comment by dhanifudin** [comment]
Pastikan repository yg kamu gunakan adalah https://github.com/polinema-gui/tugas-2015-03-ajengyunisa

**Comment by ajengyunisa** [comment]
Sudah pak, tetapi tidak bisa. Banyak juga teman-teman yang tidak bisa sync dan mendapatkan notifikasi seperti itu.

**Comment by dhanifudin** [comment]
berikan screenshoot github desktop tanpa dialog failed

**Comment by ajengyunisa** [comment]
Ini pak
![b](https://cloud.githubusercontent.com/assets/11324474/10559086/a40f8d1a-7511-11e5-829e-444092695560.JPG)

**Comment by dhanifudin** [comment]
klik kanan pada nama repository tugas-2015-03-ajengyunisa pilih menu open in git shell lakukan perintah seperti yang saya tuliskan di bawah ini
```bash
git push -u origin master
```
kemudian masukkan username dan password

**Comment by ajengyunisa** [comment]
Sudah bisa terimakasih banyak pak
